CONTACT:
  email: ''
  person: ''
LOCAL:
    temp-directory: /tmp
    memory: 4g
    raw_data: /output/raw_data
    results: /output/results
META:
    species:
        mus_musculus:
            build: 38
            release: 91
    ratio: 0.2
    reference-directory: /ref
    gtf_biotypes: /templates/gtf_biotypes.yaml

FILTER:
    barcode-whitelist: ''
    5-prime-smart-adapter: AAGCAGTGGTATCAACGCAGAGTGAATGGG
    cell-barcode:
        start: 1
        end: 12
    UMI-barcode:
        start: 13
        end: 20
    cutadapt:
        adapters-file: /templates/NexteraPE-PE.fa
        R1:
            quality-filter: 30
            maximum-Ns: 1
            extra-params: ''
        R2:
            quality-filter: 30
            minimum-adapters-overlap: 6
            minimum-length: 15
            extra-params: ''
MAPPING:
    STAR:
        genomeChrBinNbits: 18
        outFilterMismatchNmax: 10
        outFilterMismatchNoverLmax: 0.3
        outFilterMismatchNoverReadLmax: 1
        outFilterMatchNmin: 0
        outFilterMatchNminOverLread: 0.66
        outFilterScoreMinOverLread: 0.66
EXTRACTION:
    LOCUS:
        - CODING
        - UTR
    strand-strategy: SENSE
    UMI-edit-distance: 0
    minimum-counts-per-UMI: 1
