version: '3'

services:
  drop-seq-pipe:
    image: pguen/drop-seq-pipe:v0.0.6
    environment:
      - NUMCELLS=5
      - JOBS=4
      - SAMPLENAMES=sample_x1 sample2
      - DOWNSAMPLING=0   # 0 no downsampling // 1 downsampling 

      #TARGETS only executes part of the pipeline
      #possible Targets: meta, qc, filter, map, extract, all
      #- TARGETS=meta qc filter map extract all

    # use when debugging and for interactive testing
    #command: ""
    #entrypoint: "/bin/bash"
    #stdin_open: true
    #tty: true

    volumes:
      - ./fastq:/input/:ro
      #results folder 
      - ./output:/output:rw
      - ./config.yaml:/config/config.yaml
      - ./config_ds.yaml:/config/config_ds.yaml

      # if you want to replace the gtf biotypes file
      # ./gtf_biotypes.yaml:/templates/gtf_biotypes.yaml		

      # temp_folder needs to be present on the home directory of the blade	
      - /home/marc/dropseq-tmp:/tmp:rw

      # this folder will contain all the metadata generated by the
      # pipeline, this data can be re-used in subsequent analysis
      - /data/NovaSeq/bioinformatics/annotation/mouse/mm10/dropseq-indexfiles:/ref:rw
